name       : xmodmap
version    : 1.0.10
release    : 11
source     :
    - https://xorg.freedesktop.org/releases/individual/app/xmodmap-1.0.10.tar.gz : d4e9dc4cb034d0d774d059498d05348869934c52b0f24b0f3913823090b88640
license    : MIT
component  : xorg.apps
summary    : xmodmap
description: |
    X.Org Applications: xmodmap
builddeps  :
    - pkgconfig(xproto)
    - pkgconfig(x11)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
