name       : xmodmap
version    : 1.0.9
release    : 7
source     :
    - http://xorg.freedesktop.org/releases/individual/app/xmodmap-1.0.9.tar.gz : 73427a996f0fcda2a2c7ac96cfc4edd5985aeb13b48053f55ae7f63a668fadef
license    :
    - MIT
component  : xorg.apps
summary    : xmodmap
builddeps  :
    - pkgconfig(xproto)
    - pkgconfig(x11)
description: |
    X.Org Applications: xmodmap
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
